### PR TITLE
Create a full Makefile to make creating ports easier.

### PR DESCRIPTION
**Pull request by ibara**
This pull request will make creating ports for the different BSDs easier. I hope you create a port for OpenBSD. I will help if you need.

While here, I cleaned up some of the English. I hope that is OK.

### CODE REVIEW

**Comment by NanXiao** [comment]
@ibara Thanks very much for your kind review! Honestly, I don't know how to create port and never done that before. Could you create a port of lscpu? Thanks!

**Comment by ibara** [comment]
I submitted a port:
https://marc.info/?l=openbsd-ports&m=150851190414131&w=2

**Comment by ibara** [comment]
And I committed it:
https://marc.info/?l=openbsd-ports-cvs&m=150851456114960&w=2

**Comment by NanXiao** [comment]
@ibara Thanks very much for your kind help and work!

**Pull request merged**
